//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankTask.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankTask.Application.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        public static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account status..
        /// </summary>
        public static string ACCOUNT_STATUS_INVALID {
            get {
                return ResourceManager.GetString("ACCOUNT_STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account type..
        /// </summary>
        public static string ACCOUNT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audit log was created but could not be retrieved..
        /// </summary>
        public static string AUDIT_LOG_CREATION_RETRIEVAL_FAILED {
            get {
                return ResourceManager.GetString("AUDIT_LOG_CREATION_RETRIEVAL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log not found..
        /// </summary>
        public static string AUDIT_LOG_NOT_FOUND {
            get {
                return ResourceManager.GetString("AUDIT_LOG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string AUTH_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("AUTH_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must contain exactly 3 characters..
        /// </summary>
        public static string CURRENCY_INVALID {
            get {
                return ResourceManager.GetString("CURRENCY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit requires a destination account..
        /// </summary>
        public static string DEPOSIT_DESTINATION_REQUIRED {
            get {
                return ResourceManager.GetString("DEPOSIT_DESTINATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot exceed 150 characters..
        /// </summary>
        public static string EMAIL_MAX_LENGTH {
            get {
                return ResourceManager.GetString("EMAIL_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name cannot exceed 100 characters..
        /// </summary>
        public static string FULL_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("FULL_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name must be at least 3 characters..
        /// </summary>
        public static string FULL_NAME_MIN_LENGTH {
            get {
                return ResourceManager.GetString("FULL_NAME_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        public static string FULL_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("FULL_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported database type..
        /// </summary>
        public static string UNSUPPORTED_DATABASE_TYPE {
            get {
                return ResourceManager.GetString("UNSUPPORTED_DATABASE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email already exists..
        /// </summary>
        public static string USER_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required..
        /// </summary>
        public static string USER_ID_REQUIRED {
            get {
                return ResourceManager.GetString("USER_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal requires a source account..
        /// </summary>
        public static string WITHDRAWAL_SOURCE_REQUIRED {
            get {
                return ResourceManager.GetString("WITHDRAWAL_SOURCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT secret key not found..
        /// </summary>
        public static string JWT_SECRET_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("JWT_SECRET_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot exceed 100 characters..
        /// </summary>
        public static string PASSWORD_MAX_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was created but could not be retrieved..
        /// </summary>
        public static string TRANSACTION_CREATION_RETRIEVAL_FAILED {
            get {
                return ResourceManager.GetString("TRANSACTION_CREATION_RETRIEVAL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required..
        /// </summary>
        public static string TRANSACTION_CURRENCY_REQUIRED {
            get {
                return ResourceManager.GetString("TRANSACTION_CURRENCY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 500 characters..
        /// </summary>
        public static string TRANSACTION_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TRANSACTION_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
    }
}
