//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankTask.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankTask.Application.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        internal static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        internal static string AUTH_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("AUTH_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must contain exactly 3 characters..
        /// </summary>
        internal static string CURRENCY_INVALID {
            get {
                return ResourceManager.GetString("CURRENCY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit requires a destination account..
        /// </summary>
        internal static string DEPOSIT_DESTINATION_REQUIRED {
            get {
                return ResourceManager.GetString("DEPOSIT_DESTINATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT audience not found..
        /// </summary>
        internal static string JWT_AUDIENCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("JWT_AUDIENCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT issuer not found..
        /// </summary>
        internal static string JWT_ISSUER_NOT_FOUND {
            get {
                return ResourceManager.GetString("JWT_ISSUER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT secret key cannot be empty..
        /// </summary>
        internal static string JWT_SECRET_KEY_EMPTY {
            get {
                return ResourceManager.GetString("JWT_SECRET_KEY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT secret key not found..
        /// </summary>
        internal static string JWT_SECRET_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("JWT_SECRET_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL connection string not found..
        /// </summary>
        internal static string POSTGRESQL_CONNECTION_STRING_NOT_FOUND {
            get {
                return ResourceManager.GetString("POSTGRESQL_CONNECTION_STRING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlServer connection string not found..
        /// </summary>
        internal static string SQLSERVER_CONNECTION_STRING_NOT_FOUND {
            get {
                return ResourceManager.GetString("SQLSERVER_CONNECTION_STRING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount must be greater than zero..
        /// </summary>
        internal static string TRANSACTION_AMOUNT_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_AMOUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was created but could not be retrieved..
        /// </summary>
        internal static string TRANSACTION_CREATION_RETRIEVAL_FAILED {
            get {
                return ResourceManager.GetString("TRANSACTION_CREATION_RETRIEVAL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found..
        /// </summary>
        internal static string TRANSACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction type..
        /// </summary>
        internal static string TRANSACTION_TYPE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and destination accounts must be different..
        /// </summary>
        internal static string TRANSFER_ACCOUNTS_MUST_DIFFER {
            get {
                return ResourceManager.GetString("TRANSFER_ACCOUNTS_MUST_DIFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer requires both source and destination accounts..
        /// </summary>
        internal static string TRANSFER_ACCOUNTS_REQUIRED {
            get {
                return ResourceManager.GetString("TRANSFER_ACCOUNTS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported database type..
        /// </summary>
        internal static string UNSUPPORTED_DATABASE_TYPE {
            get {
                return ResourceManager.GetString("UNSUPPORTED_DATABASE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email already exists..
        /// </summary>
        internal static string USER_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal requires a source account..
        /// </summary>
        internal static string WITHDRAWAL_SOURCE_REQUIRED {
            get {
                return ResourceManager.GetString("WITHDRAWAL_SOURCE_REQUIRED", resourceCulture);
            }
        }
    }
}
